#include "type.h"
#include "stdio.h"
#include "const.h"
#include "protect.h"
#include "string.h"
#include "fs.h"
#include "proc.h"
#include "tty.h"
#include "console.h"
#include "global.h"
#include "proto.h"

/*****************************************************************************
 *                                animation
 *****************************************************************************/
/**
 * An animation 
 *
 *****************************************************************************/

 PUBLIC void animation()
 {
 // int i = 0;
 // clear();                                                                      
 // printf("                                             ,::,.                           \n");     
 // printf("                                        .71XSS5kr                          \n");
 // printf("                                       LGG0XkFk12;YY                         \n");
 // printf("                                      UL2GN0P0Pk27rXi                        \n");
 // printf("                                     L8jP0M8MNq5522ki                        \n");
 // printf("                                     qOGq8OBO8XPFSNk                         \n");
 // printf("                                     UB8OOBBB8GN8MG.                         \n");
 // printf("                                     EBBBBZqBBBBJ                            \n");
 // printf("                                       :kBBBBBNi                             \n");
 // printf("                                         .jU7                                \n");
 // printf("                                  ,7Liiir7rir7.                              \n");
 // printf("                                 2BBBBBBBBq5:,u:                             \n");
 // printf("                                UBMU.iBZM0NSU 7Y                             \n");
 // printf("                              :U212  ::L12U5UY27  .JXS7                      \n");
 // printf("                            .FBNUvi :i7q0XN1UYri:UBBBBB.                     \n");
 // printf("                            iBBBBZ .XSNNkPFUuu::qBBBBM:                      \n");
 // printf("                             :8Ej  rGSqXqkSU1SNkY.                           \n");
 // printf("                                   UOGZOXX5PqZEM,                            \n");
 // printf("                                   iBBB80qGZ8kk:                             \n");
 // printf("                                    iBBBBO1NEq7                              \n");
 // printf("                                     :BO2irYUL.                              \n");
 // printf("                                     .5Xr2GqYv7i                             \n");
 // printf("                                  ..75GBBBBBBBBN1Y:                          \n");
 // printf("                             JSFj1ZBBBBBBr .YBBBBB;                          \n");
 // printf("                            .BBBBBBBBBBj       ,i.                           \n");
 // printf("     ..,:::i:i:::::i:i::::::.rEM8MMEUX2                                      \n");
 // printf("      ................... .                                                \n");
 // milli_delay(15000);                                                                                                                            
 
 // clear();                                                                                         
 // printf("                                       .:77Yvr,                              \n");
 // printf("                                     .uN5U2u5Ui                            \n");
 // printf("                                    .2UEXP5XUUi:Ui                           \n");
 // printf("                                    EUuNGN0kFUYr2U                           \n");
 // printf("                                   .M8N0EMZqFFUU1U                           \n");
 // printf("                                    XBOZMBBGNkPqZ,                           \n");
 // printf("                                     0BBBB2BBBBG.                            \n");
 // printf("                                      :uGMkkqU:                              \n");
 // printf("                                        .7rr                                 \n");
 // printf("                                  YY7::JU77rY:                               \n");
 // printf("                                iBBBBPi7NqF;:5.                              \n");
 // printf("                               7BBB,7i:X800urU:                              \n");
 // printf("                             .2BBB  r.1q1XS17Y.    i77:                      \n");
 // printf("                            iMBBBB;r:7GXk15UY7vLUE8ZB8G:                     \n");
 // printf("                            :BBBBOj7,PkPSF1qE8GBBBBBBBq.                     \n");
 // printf("                              ::. :k0PX52juFBBBBi :7L:                       \n");
 // printf("                                  LB8Ek5L7r0BBBB                             \n");
 // printf("                                  .GBM8FY;rkBMX                              \n");
 // printf("                                    UBOG27iYMU                               \n");
 // printf("                                     uMEqY77.                                \n");
 // printf("                                     :EO0FL;                                 \n");
 // printf("                                    .7NGOFUJLi                               \n");
 // printf("                               ..,rUSPXZSkBBMZu                              \n");
 // printf("                             2OqqXNNZNP5  :MBBS                              \n");
 // printf("     ..:,:::,:,:,:,:,:,:,:,.rBBBBBBMNNSY                                     \n");
 // printf("    ..:::::::,,............                                                  \n");
 // milli_delay(15000);                                                                                         
                                                                            
 // clear();                                                                                          
 // printf("                                                 .::i:,                      \n");
 // printf("                                            :uP0FS1S12r                      \n");
 // printf("                                          .j00EqPSPF5;LY                     \n");
 // printf("                                         .PLrENGEGqX2jYk:                    \n");
 // printf("                                         jOk0qE8MZEkkUSX.                    \n");
 // printf("                                         XOENG8BBM00X0OY                     \n");
 // printf("                                         .MOMMBMXOBMBBL                      \n");
 // printf("                                   iv15J. iFNBBMBBBBG.                       \n");
 // printf("                            ,LYirj0BBBBBBF7;rrLv1r:   .                      \n");
 // printf("                           rBBO2YZ8Ui .2MBMEJriv    :OB8v                    \n");
 // printf("                           :BBBBMj.     FN8qFu7:v  .8BBB2                    \n");
 // printf("                             7u7.      LUUYuU5rrL ,MBBqr                     \n");
 // printf("                                      LLS1F15uuLY2ZEJ                        \n");
 // printf("                                     77rPqXP2UYuMBZ.                         \n");
 // printf("                                    .P1NZq0k52X7,,                           \n");
 // printf("                                    78NG0q52UXr                              \n");
 // printf("                                    r8ZEGP5L7r                               \n");
 // printf("                                    iOqOMM0kL:::                             \n");
 // printf("                                    vPMMBBBBON5jL.     iqPL                  \n");
 // printf("                                  :kEBBBE:JBBBBMkY:   :XMMq.                 \n");
 // printf("                                :UOBBBBL    :ZBBBBX7::UPMZr                  \n");
 // printf("                           ..iuqMBBBBS         7NBBBMkYUFj                   \n");
 // printf("                         FMk1EBBB82:              vBBBBBX                    \n");
 // printf("                         OBB2YJi                    :OBq.                    \n");
 // printf("                          ZBM1Y:                                             \n");
 // printf("       ..::::::::::i::::,.:8MGkY ...............                             \n");
 // printf("       ..................         . . . . . .                              \n");
 // milli_delay(15000);
 
 // clear();
 // printf("                                           .i7YLv;:                          \n");  
 // printf("                                         7XZkk12212U:                        \n");
 // printf("                                        UUXN0kXSFUriS,                       \n");
 // printf("                                       j0LSGGGEEkFYY2Y                       \n");
 // printf("                                       qM0GEMMMEq5Sr                       \n");
 // printf("                                       7BOGMMBMMEN0MF                        \n");
 // printf("                                   ,i,  jEMBBMZBBBBL                         \n");
 // printf("                             ...:qBBBBB2rr7uXPqB                           \n");
 // printf("                           UB82LNBBUrXBBO5Ji,:L     .,,                      \n");
 // printf("                          ,BBBGqPr    7MMBEk:,J    jMBZU                     \n");
 // printf("                           2BBBj.     YjS2127iU   1BBBBJ                     \n");
 // printf("                                      Yiu5UUU7vY.,8BBkY.                      \n");
 // printf("                                    iU7qNSXujLjZBqJ.                         \n");
 // printf("                                    FP0GN0kFu2UBY                            \n");
 // printf("                                   iZqGNN51J1j                               \n");
 // printf("                                   1MZGONSJL7,                               \n");
 // printf("                                   iBOMMBEFY;:.                              \n");
 // printf("                                    5BOMMBBMq1Y:                             \n");
 // printf("                                    v0BBBBBBBBEJ7                            \n");
 // printf("                                  .72MBBB  YBBBMF7.                          \n");
 // printf("                         .UUY7LjU5EZOBBB.    JBBBGXi                         \n");
 // printf("                         LBBNFXOBBBBB0i        :BBBPY7rJJU1Nu.               \n");
 // printf("                          JBBMkjPr.              7BBBMMBBBBB8                \n");
 // printf(" :i::::i:::::i:i:::::i:::. LMBP2r      .........  iMBBEOkur:                 \n");
 // printf(" ,:,:,,,,.,..............               .                                  \n");
 // milli_delay(15000);
 
 // clear();                                                                                          
 // printf("                                         .ir7ri.                             \n");
 // printf("                                       iF8qX1S1kU:                           \n");
 // printf("                                      jP8EqXq557i1r                          \n");
 // printf("                                     YkLEMZG0P5JiUk.                         \n");
 // printf("                                     XMEZ8B88XP15UN                          \n");
 // printf("                                     kBMGBBBO8NNXMv                          \n");
 // printf("                                     .BBBBBBBMBBBj                           \n");
 // printf("                                       5q8GZSUSS,                            \n");
 // printf("                                       iuv7rvrv                              \n");
 // printf("                                      7S21UU .U.                             \n");
 // printf("                                     7FJGqXU .X.                             \n");
 // printf("                                   ,ULrZEEXUvUU                              \n");
 // printf("                                  ,MqrkGGNPUYr7  .ii,                        \n");
 // printf("                                   U2qG800XPF52ZXMBBN:                       \n");
 // printf("                                   5ZGM8ZPNMBBBBBBBBB.                       \n");
 // printf("                                  :BGMM8XUkBk. i1MqL                         \n");
 // printf("                                   BBMBEF7PB                                 \n");
 // printf("                                   ,MBMO1LvX                                 \n");
 // printf("                                    :MMZXLLui                                \n");
 // printf("                                     YUFuYYX;                                \n");
 // printf("                                 .:7XqZ2YL1k.                                \n");
 // printf("                           ,USU1NMBBBBBB8ZSU                                 \n");
 // printf("                           BBBN58BBBkr  MBGU                                 \n");
 // printf("                           7BBNY::      5MPY.                                \n");
 // printf("                            iBBBUv     7BZXFEEG0X;                           \n");
 // printf(" .   ..:::::::,:,:,:::,:,:.. qBBMk:....28ZSXNNFS2v                           \n");
 // printf("  . ....,.............. . .                                                \n");
 //  milli_delay(15000);
 
 //  clear();                                                     
 // printf("                                            ,::,.                            \n");
 // printf("                                        .71XSS5kr                          \n");
 // printf("                                       LGG0XkFk12;YY                         \n");
 // printf("                                      UL2GN0P0Pk27rXi                        \n");
 // printf("                                     L8jP0M8MNq5522ki                        \n");
 // printf("                                     qOGq8OBO8XPFSNk                         \n");
 // printf("                                     UB8OOBBB8GN8MG.                         \n");
 // printf("                                      EBBBBZqBBBBJ                           \n");
 // printf("                                       :kBBBBBNi                             \n");
 // printf("                                         .jU7                                \n");
 // printf("                                  ,7Liiir7rir7.                              \n");
 // printf("                                 2BBBBBBBBq5:,u:                             \n");
 // printf("                                UBMU.iBZM0NSU 7Y                             \n");
 // printf("                              :U212  ::L12U5UY27  .JXS7                      \n");
 // printf("                            .FBNUvi :i7q0XN1UYri:UBBBBB.                     \n");
 // printf("                            iBBBBZ .XSNNkPFUuu::qBBBBM:                      \n");
 // printf("                             :8Ej  rGSqXqkSU1SNkY.                           \n");
 // printf("                                   UOGZOXX5PqZEM,                            \n");
 // printf("                                   iBBB80qGZ8kk:                             \n");
 // printf("                                    iBBBBO1NEq7                              \n");
 // printf("                                     :BO2irYUL.                              \n");
 // printf("                                     .5Xr2GqYv7i                             \n");
 // printf("                                  ..75GBBBBBBBBN1Y:                          \n");
 // printf("                             JSFj1ZBBBBBBr .YBBBBB;                          \n");
 // printf("                            .BBBBBBBBBBj       ,i.                           \n");
 // printf("     ..,:::i:i:::::i:i::::::.rEM8MMEUX2                                      \n");
 // printf("      ................... .                                                \n");
 // milli_delay(15000);
	clear();
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("       =====        ________                ___________                      \n");
	printf("   _D _|  | _______/        \\__I_I_____===__|________|                       \n");
	printf("    |(_)      |   H\\________/ |   |        =|___ ___|      _________________ \n");
	printf("    /     |   |   H  |  |     |   |         ||_| |_||     _|                \\\n");
	printf("   |      |   |   H  |__                    | | __| |   =|                   \n");
	printf("   | _ _______|___H__/__|_____/[][]~\\_______|       |    |                   \n");
	printf("   |/ |   |            I_____I [][] []  D   | ======|____|___________________\n");
	printf(" __/ =|   | = 0=====0=====0=====0 \\ ____Y___________|__|_____________________\n");
	printf("  |/ =|___| =    ||    ||    ||    |_____/~\\___/          |_D__D__D_|  |_D__D\n");
	printf("   \\_/       \\__/  \\__/  \\__/  \\__/      \\_/               \\_/   \\_/    \\_/   \n");
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("\n");
	printf("\n");
	printf("\n");
    printf("                                     Welcome !          \n");
    printf("\n");
    printf("\n");
    printf("\n");
    printf("=============================================================================\n");
	milli_delay(15000);

	clear();
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("       =====        ________                ___________                      \n");
	printf("   _D _|  | _______/        \\__I_I_____===__|________|                       \n");
	printf("    |(_)      |   H\\________/ |   |        =|___ ___|      _________________ \n");
	printf("    /     |   |   H  |  |     |   |         ||_| |_||     _|                \\\n");
	printf("   |      |   |   H  |__                    | | __| |   =|                   \n");
	printf("   | _ _______|___H__/__|_____/[][]~\\_______|       |    |                   \n");
	printf("   |/ |   |            I_____I [][] []  D   | ======|____|___________________\n");
	printf(" __/ =|   | =/~~\\  /~~\\  /~~\\  /~~\\ ____Y___________|__|_____________________\n");
	printf("  |/ =|___| =0=====0=====0=====0   |_____/~\\___/          |_D__D__D_|  |_D__D\n");
	printf("   \\_/       \\__/  \\__/  \\__/  \\__/      \\_/               \\_/   \\_/    \\_/   \n");
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("\n");
	printf("\n");
	printf("\n");
    printf("                                     Welcome !          \n");
    printf("\n");
    printf("\n");
    printf("\n");
    printf("=============================================================================\n");
	milli_delay(15000);

	clear();
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("       =====        ________                ___________                      \n");
	printf("   _D _|  | _______/        \\__I_I_____===__|________|                       \n");
	printf("    |(_)      |   H\\________/ |   |        =|___ ___|      _________________ \n");
	printf("    /     |   |   H  |  |     |   |         ||_| |_||     _|                \\\n");
	printf("   |      |   |   H  |__                    | | __| |   =|                   \n");
	printf("   | _ _______|___H__/__|_____/[][]~\\_______|       |    |                   \n");
	printf("   |/ |   |            I_____I [][] []  D   | ======|____|___________________\n");
	printf(" __/ =|   | =/~~\\  /~~\\  /~~\\  /~~\\ ____Y___________|__|_____________________\n");
	printf("  |/ =|___| =    ||    ||    ||    |_____/~\\___/          |_D__D__D_|  |_D__D\n");
	printf("   \\_/        0=====0=====0=====0_/      \\_/               \\_/   \\_/    \\_/   \n");
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("\n");
	printf("\n");
	printf("\n");
    printf("                                     Welcome !          \n");
    printf("\n");
    printf("\n");
    printf("\n");
    printf("=============================================================================\n");
	milli_delay(15000);

	clear();
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("       =====        ________                ___________                      \n");
	printf("   _D _|  | _______/        \\__I_I_____===__|________|                       \n");
	printf("    |(_)      |   H\\________/ |   |        =|___ ___|      _________________ \n");
	printf("    /     |   |   H  |  |     |   |         ||_| |_||     _|                \\\n");
	printf("   |      |   |   H  |__                    | | __| |   =|                   \n");
	printf("   | _ _______|___H__/__|_____/[][]~\\_______|       |    |                   \n");
	printf("   |/ |   |            I_____I [][] []  D   | ======|____|___________________\n");
	printf(" __/ =|   | =/~~\\  /~~\\  /~~\\  /~~\\ ____Y___________|__|_____________________\n");
	printf("  |/ =|___| =    ||    ||    ||    |_____/~\\___/          |_D__D__D_|  |_D__D\n");
	printf("   \\_/       \\_0=====0=====0=====0       \\_/               \\_/   \\_/    \\_/   \n");
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("\n");
	printf("\n");
	printf("\n");
    printf("                                     Welcome !          \n");
    printf("\n");
    printf("\n");
    printf("\n");
    printf("=============================================================================\n");
	milli_delay(15000);

	clear();
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("       =====        ________                ___________                      \n");
	printf("   _D _|  | _______/        \\__I_I_____===__|________|                       \n");
	printf("    |(_)      |   H\\________/ |   |        =|___ ___|      _________________ \n");
	printf("    /     |   |   H  |  |     |   |         ||_| |_||     _|                \\\n");
	printf("   |      |   |   H  |__                    | | __| |   =|                   \n");
	printf("   | _ _______|___H__/__|_____/[][]~\\_______|       |    |                   \n");
	printf("   |/ |   |            I_____I [][] []  D   | ======|____|___________________\n");
	printf(" __/ =|   | =/~~\\  /~~\\  /~~\\  /~~\\ ____Y___________|__|_____________________\n");
	printf("  |/ =|___| =   0=====0=====0=====0|_____/~\\___/          |_D__D__D_|  |_D__D\n");
	printf("   \\_/       \\__/  \\__/  \\__/  \\__/      \\_/               \\_/   \\_/    \\_/   \n");
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("\n");
	printf("\n");
	printf("\n");
    printf("                                     Welcome !          \n");
    printf("\n");
    printf("\n");
    printf("\n");
    printf("=============================================================================\n");
	milli_delay(15000);

	clear();
	printf("=============================================================================\n");
	printf("=============================================================================\n");
	printf("       =====        ________                ___________                      \n");
	printf("   _D _|  | _______/        \\__I_I_____===__|________|                      \n");
	printf("    |(_)      |   H\\________/ |   |        =|___ ___|      _________________ \n");
	printf("    /     |   |   H  |  |     |   |         ||_| |_||     _|                \\\n");
	printf("   |      |   |   H  |__                    | | __| |   =|                   \n");
	printf("   | _ _______|___H__/__|_____/[][]~\\_______|       |    |                   \n");
	printf("   |/ |   |            I_____I [][] []  D   | ======|____|___________________\n");
	printf(" __/ =|   | =/~~0=====0=====0=====0 ____Y___________|__|_____________________\n");
	printf("  |/ =|___| =    ||    ||    ||    |_____/~\\___/          |_D__D__D_|  |_D__D\n");
	printf("   \\_/       \\__/  \\__/  \\__/  \\__/      \\_/               \\_/   \\_/    \\_/   \n");
	printf("=============================================================================\n");	
	printf("=============================================================================\n");
	printf("\n");
	printf("\n");
	printf("\n");
    printf("                                     Welcome !          \n");
    printf("\n");
    printf("\n");
    printf("\n");
    printf("=============================================================================\n");
	milli_delay(15000);
 	clear();
 }